### ISSUE TITLE
🍣🍣🍣🍣🍣🍣🍣🍣🍣🍣🍣🍣🍣🍣

### ISSUE THREAD

**Issue by surume** [a-know/a-know-sushi#1]
背景a-knowさま。
最終🍣後、お日にちが経過いたしましたが、
その後ご状況いかがでしょうか。

近況等ざっくばらんにお話できたらと思い
🍣Rを出させて頂きました。

もしよろしければ🍣の機会を頂けますでしょうか？
お時間などはいつでも構いません。
恐れ入りますが、お🍣の程何卒よろしくお願い致します。

**Comment by a-know** [comment]
🍣 R thx!!

いいですね、どうせなら他の人にも声かけますか！
以降は Twitter DM で！

**Comment by surume** [comment]
👍
